# Lecture 8 - Pandas Fundamentals

This week you will be introduced to pandas, which is a library dedicated to processing large datasets simply and efficiently. Pandas can be imported by running the Python cell below.

In [1]:
import pandas as pd

## Importing Data
For this lecture we will be analysing the 'LSTM-Multivariate_pollution.csv' dataset. The <code>read_csv</code> function from pandas is called below to import the data.

In [2]:
# import the data using the read_csv function
pollution_data = pd.read_csv('Data/LSTM-Multivariate_pollution.csv', index_col='date')
pollution_data

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
2/01/2010 0:00          129  -16  -4.0  1020.0      SE     1.79     0     0
2/01/2010 1:00          148  -15  -4.0  1020.0      SE     2.68     0     0
2/01/2010 2:00          159  -11  -5.0  1021.0      SE     3.57     0     0
2/01/2010 3:00          181   -7  -5.0  1022.0      SE     5.36     1     0
2/01/2010 4:00          138   -7  -5.0  1022.0      SE     6.25     2     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
31/12/2014 19:00          8  -23  -2.0  1034.0      NW   231.97     0     0
31/12/2014 20:00         10  -22  -3.0  1034.0      NW   237.78     0     0
31/12/2014 21:00         10  -22  -3.0  1034.0      NW   242.70     0     0
31/12/2014 22:00          8  -22  -4.0  1034.0      NW   246.72     0     0
31/12/2014 23:00         12  -21  -3.0  1034.0      NW   249.85     0     0

[43800 rows x 8 columns]

## Inspecting Data
Use data inspection tools to answer the following questions:
1. How many observations are in the data? 43800
2. How many columns are in the data? 8
3. What are the column names?
4. What is the data type of each column?
5. What is the dataframe index? What data type does it have? 2/01/2010 0:00 to 31/12/2014 23:00

In [3]:
# insert data inspection code
pollution_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43800 entries, 2/01/2010 0:00 to 31/12/2014 23:00
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pollution  43800 non-null  int64
 1   dew        43800 non-null  int64
 2   temp       43800 non-null  float64
 3   press      43800 non-null  float64
 4   wnd_dir    43800 non-null  object
 5   wnd_spd    43800 non-null  float64
 6   snow       43800 non-null  int64
 7   rain       43800 non-null  int64
dtypes: float64(3), int64(4), object(1)
memory usage: 3.0+ MB

In [4]:
pollution_data.index

Index(['2/01/2010 0:00', '2/01/2010 1:00', '2/01/2010 2:00', '2/01/2010 3:00',
       '2/01/2010 4:00', '2/01/2010 5:00', '2/01/2010 6:00', '2/01/2010 7:00',
       '2/01/2010 8:00', '2/01/2010 9:00',
       ...
       '31/12/2014 14:00', '31/12/2014 15:00', '31/12/2014 16:00',
       '31/12/2014 17:00', '31/12/2014 18:00', '31/12/2014 19:00',
       '31/12/2014 20:00', '31/12/2014 21:00', '31/12/2014 22:00',
       '31/12/2014 23:00'],
      dtype='object', name='date', length=43800)

In [5]:
pollution_data.describe()

,pollution,dew,temp,press,wnd_spd,snow,rain
count,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000,43800.000000
mean,94.013516,1.828516,12.459041,1016.447306,23.894307,0.052763,0.195023
std,92.252276,14.429326,12.193384,10.271411,50.022729,0.760582,1.416247
min,0.000000,-40.000000,-19.000000,991.000000,0.450000,0.000000,0.000000
25%,24.000000,-10.000000,2.000000,1008.000000,1.790000,0.000000,0.000000
50%,68.000000,2.000000,14.000000,1016.000000,5.370000,0.000000,0.000000
75%,132.250000,15.000000,23.000000,1025.000000,21.910000,0.000000,0.000000
max,994.000000,28.000000,42.000000,1046.000000,585.600000,27.000000,36.000000

## Selecting Data
Data can be selected by label using <code>loc</code> or by index using <code>iloc</code>.

General syntax for <code>loc</code> is </code>df_name.loc[row_label, col_label]</code>

General syntax for <code>iloc</code> is </code>df_name.iloc[row_index, col_index]</code>

In [6]:
# select the temp column
pollution_data.temp

date
2/01/2010 0:00     -4.0
2/01/2010 1:00     -4.0
2/01/2010 2:00     -5.0
2/01/2010 3:00     -5.0
2/01/2010 4:00     -5.0
                   ...
31/12/2014 19:00   -2.0
31/12/2014 20:00   -3.0
31/12/2014 21:00   -3.0
31/12/2014 22:00   -4.0
31/12/2014 23:00   -3.0
Name: temp, Length: 43800, dtype: float64

In [7]:
pollution_data['temp']

date
2/01/2010 0:00     -4.0
2/01/2010 1:00     -4.0
2/01/2010 2:00     -5.0
2/01/2010 3:00     -5.0
2/01/2010 4:00     -5.0
                   ...
31/12/2014 19:00   -2.0
31/12/2014 20:00   -3.0
31/12/2014 21:00   -3.0
31/12/2014 22:00   -4.0
31/12/2014 23:00   -3.0
Name: temp, Length: 43800, dtype: float64

In [8]:
pollution_data.loc[:, 'temp']

date
2/01/2010 0:00     -4.0
2/01/2010 1:00     -4.0
2/01/2010 2:00     -5.0
2/01/2010 3:00     -5.0
2/01/2010 4:00     -5.0
                   ...
31/12/2014 19:00   -2.0
31/12/2014 20:00   -3.0
31/12/2014 21:00   -3.0
31/12/2014 22:00   -4.0
31/12/2014 23:00   -3.0
Name: temp, Length: 43800, dtype: float64

In [9]:
# select the row at 1/01/2012 0:00
pollution_data.loc['1/01/2012 0:00']

pollution       275
dew             -12
temp           -8.0
press        1030.0
wnd_dir          NE
wnd_spd        0.89
snow              0
rain              0
Name: 1/01/2012 0:00, dtype: object

In [10]:
pollution_data.loc['1/01/2012 0:00', :]

pollution       275
dew             -12
temp           -8.0
press        1030.0
wnd_dir          NE
wnd_spd        0.89
snow              0
rain              0
Name: 1/01/2012 0:00, dtype: object

In [11]:
# select the pollution at 5/03/2013 21:00
pollution_data.loc['5/03/2013 21:00', 'pollution']

np.int64(263)

In [12]:
# select all observations from March 2011
pollution_data.loc['1/03/2011 0:00': '31/03/2011 23:00', :]

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
1/03/2011 0:00           12  -11  -1.0  1028.0      NW    93.44     0     0
1/03/2011 1:00            9  -12  -2.0  1028.0      NE     3.13     0     0
1/03/2011 2:00            9  -12  -4.0  1028.0      NW     3.13     0     0
1/03/2011 3:00           11  -12  -4.0  1028.0      NW     6.26     0     0
1/03/2011 4:00           17  -12  -3.0  1028.0      NW     8.05     0     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
31/03/2011 19:00          0    4  17.0  1013.0      cv     1.78     0     0
31/03/2011 20:00          0    4  14.0  1014.0      NE     0.89     0     0
31/03/2011 21:00        295    4  12.0  1015.0      cv     0.89     0     0
31/03/2011 22:00        328    3  14.0  1016.0      NE     3.13     0     0
31/03/2011 23:00        287    3  14.0  1016.0      NE     6.26     0     0

[744 rows x 8 columns]

In [13]:
# select the element in the 100th row and the 4th column
pollution_data.iloc[99, 3]

np.float64(1033.0)

## Filtering Data
Data can be filtered using Boolean arrays just like you saw with NumPy arrays last week. This allows for data to be selected if a certain condition is True. 

The general syntax is <code>df_name[condition]</code> and reads select the dataframe for each row where the condition is True.

In [14]:
# select all rows where the temperature is below zero

# select the rows of pollution_data where the temp column of pollultion_data is less than zero
pollution_data[pollution_data.temp < 0]

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
2/01/2010 0:00          129  -16  -4.0  1020.0      SE     1.79     0     0
2/01/2010 1:00          148  -15  -4.0  1020.0      SE     2.68     0     0
2/01/2010 2:00          159  -11  -5.0  1021.0      SE     3.57     0     0
2/01/2010 3:00          181   -7  -5.0  1022.0      SE     5.36     1     0
2/01/2010 4:00          138   -7  -5.0  1022.0      SE     6.25     2     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
31/12/2014 19:00          8  -23  -2.0  1034.0      NW   231.97     0     0
31/12/2014 20:00         10  -22  -3.0  1034.0      NW   237.78     0     0
31/12/2014 21:00         10  -22  -3.0  1034.0      NW   242.70     0     0
31/12/2014 22:00          8  -22  -4.0  1034.0      NW   246.72     0     0
31/12/2014 23:00         12  -21  -3.0  1034.0      NW   249.85     0     0

[8590 rows x 8 columns]

In [15]:
below_zero = pollution_data.temp < 0
pollution_data[below_zero]

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
2/01/2010 0:00          129  -16  -4.0  1020.0      SE     1.79     0     0
2/01/2010 1:00          148  -15  -4.0  1020.0      SE     2.68     0     0
2/01/2010 2:00          159  -11  -5.0  1021.0      SE     3.57     0     0
2/01/2010 3:00          181   -7  -5.0  1022.0      SE     5.36     1     0
2/01/2010 4:00          138   -7  -5.0  1022.0      SE     6.25     2     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
31/12/2014 19:00          8  -23  -2.0  1034.0      NW   231.97     0     0
31/12/2014 20:00         10  -22  -3.0  1034.0      NW   237.78     0     0
31/12/2014 21:00         10  -22  -3.0  1034.0      NW   242.70     0     0
31/12/2014 22:00          8  -22  -4.0  1034.0      NW   246.72     0     0
31/12/2014 23:00         12  -21  -3.0  1034.0      NW   249.85     0     0

[8590 rows x 8 columns]

In [16]:
# select all the rows where there is snow
is_snow = pollution_data.snow > 0
pollution_data[is_snow]

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
2/01/2010 3:00          181   -7  -5.0  1022.0      SE     5.36     1     0
2/01/2010 4:00          138   -7  -5.0  1022.0      SE     6.25     2     0
2/01/2010 5:00          109   -7  -6.0  1022.0      SE     7.14     3     0
2/01/2010 6:00          105   -7  -6.0  1023.0      SE     8.93     4     0
2/01/2010 10:00         140   -7  -5.0  1026.0      SE    17.43     1     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
13/02/2014 10:00        205  -11  -3.0  1038.0      SE    57.67     2     0
18/02/2014 23:00        123  -11  -2.0  1029.0      SE     2.68     1     0
20/02/2014 8:00         184   -5  -2.0  1032.0      SE     3.57     1     0
20/02/2014 9:00         190   -5  -1.0  1032.0      SE     5.36     2     0
10/12/2014 0:00         311   -6  -1.0  1029.0      cv     0.89     1     0

[368 rows x 8 columns]

In [17]:
# select all rows that are below zero and don't have snow 
# & = and
# | = or
# ~ = not

pollution_data[below_zero & ~is_snow]

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
2/01/2010 0:00          129  -16  -4.0  1020.0      SE     1.79     0     0
2/01/2010 1:00          148  -15  -4.0  1020.0      SE     2.68     0     0
2/01/2010 2:00          159  -11  -5.0  1021.0      SE     3.57     0     0
2/01/2010 7:00          124   -7  -5.0  1024.0      SE    10.72     0     0
2/01/2010 8:00          120   -8  -6.0  1024.0      SE    12.51     0     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
31/12/2014 19:00          8  -23  -2.0  1034.0      NW   231.97     0     0
31/12/2014 20:00         10  -22  -3.0  1034.0      NW   237.78     0     0
31/12/2014 21:00         10  -22  -3.0  1034.0      NW   242.70     0     0
31/12/2014 22:00          8  -22  -4.0  1034.0      NW   246.72     0     0
31/12/2014 23:00         12  -21  -3.0  1034.0      NW   249.85     0     0

[8276 rows x 8 columns]

In [18]:
# select all rows that have rain or snow
is_rain = pollution_data.rain > 0
pollution_data[is_rain | is_snow]

                  pollution  dew  temp   press wnd_dir  wnd_spd  snow  rain
date
2/01/2010 3:00          181   -7  -5.0  1022.0      SE     5.36     1     0
2/01/2010 4:00          138   -7  -5.0  1022.0      SE     6.25     2     0
2/01/2010 5:00          109   -7  -6.0  1022.0      SE     7.14     3     0
2/01/2010 6:00          105   -7  -6.0  1023.0      SE     8.93     4     0
2/01/2010 10:00         140   -7  -5.0  1026.0      SE    17.43     1     0
...                     ...  ...   ...     ...     ...      ...   ...   ...
31/10/2014 11:00        150   10  14.0  1021.0      cv     3.57     0     1
31/10/2014 13:00        143   10  15.0  1020.0      SE     3.58     0     1
31/10/2014 14:00        143   10  15.0  1019.0      SE     5.37     0     2
29/11/2014 18:00        343    2   4.0  1020.0      NE     0.89     0     1
10/12/2014 0:00         311   -6  -1.0  1029.0      cv     0.89     1     0

[2176 rows x 8 columns]

## Computed Columns
A computed column is a column that is calculated based on other columns in the dataframe. These are generally calculated by using element-wise operators (you should remember these from when you learned about arrays). If you need to define you own custom function for computations, it can be applied element-wise by calling the <code>apply</code> method.

In [19]:
# create a new column that includes the pressure measured in atmospheres 
# (note: the current pressure column is measured in millibars).
pollution_data['press_atm'] = pollution_data.press * 0.00098692
pollution_data

,pollution,dew,temp,press,wnd_dir,wnd_spd,snow,rain,press_atm
date,,,,,,,,,
2/01/2010 0:00,129,-16,-4.0,1020.0,SE,1.79,0,0,1.006658
2/01/2010 1:00,148,-15,-4.0,1020.0,SE,2.68,0,0,1.006658
2/01/2010 2:00,159,-11,-5.0,1021.0,SE,3.57,0,0,1.007645
2/01/2010 3:00,181,-7,-5.0,1022.0,SE,5.36,1,0,1.008632
2/01/2010 4:00,138,-7,-5.0,1022.0,SE,6.25,2,0,1.008632
...,...,...,...,...,...,...,...,...,...
31/12/2014 19:00,8,-23,-2.0,1034.0,NW,231.97,0,0,1.020475
31/12/2014 20:00,10,-22,-3.0,1034.0,NW,237.78,0,0,1.020475
31/12/2014 21:00,10,-22,-3.0,1034.0,NW,242.70,0,0,1.020475
31/12/2014 22:00,8,-22,-4.0,1034.0,NW,246.72,0,0,1.020475
31/12/2014 23:00,12,-21,-3.0,1034.0,NW,249.85,0,0,1.020475

In [20]:
# create a new column that specified whether the temperatures is above or below freezing point (0 degrees)
pollution_data['is_freezing'] = pollution_data.temp <= 0
pollution_data

,pollution,dew,temp,press,wnd_dir,wnd_spd,snow,rain,press_atm,is_freezing
date,,,,,,,,,,
2/01/2010 0:00,129,-16,-4.0,1020.0,SE,1.79,0,0,1.006658,True
2/01/2010 1:00,148,-15,-4.0,1020.0,SE,2.68,0,0,1.006658,True
2/01/2010 2:00,159,-11,-5.0,1021.0,SE,3.57,0,0,1.007645,True
2/01/2010 3:00,181,-7,-5.0,1022.0,SE,5.36,1,0,1.008632,True
2/01/2010 4:00,138,-7,-5.0,1022.0,SE,6.25,2,0,1.008632,True
...,...,...,...,...,...,...,...,...,...,...
31/12/2014 19:00,8,-23,-2.0,1034.0,NW,231.97,0,0,1.020475,True
31/12/2014 20:00,10,-22,-3.0,1034.0,NW,237.78,0,0,1.020475,True
31/12/2014 21:00,10,-22,-3.0,1034.0,NW,242.70,0,0,1.020475,True
31/12/2014 22:00,8,-22,-4.0,1034.0,NW,246.72,0,0,1.020475,True
31/12/2014 23:00,12,-21,-3.0,1034.0,NW,249.85,0,0,1.020475,True

In [21]:
# doesn't work elementwise by default - need apply method
def is_raining(df):
    if df.rain > 0:
        return 'yes'
    else:
        return 'no'

pollution_data['is_rain'] = pollution_data.apply(is_raining, axis=1)
pollution_data

,pollution,dew,temp,press,wnd_dir,wnd_spd,snow,rain,press_atm,is_freezing,is_rain
date,,,,,,,,,,,
2/01/2010 0:00,129,-16,-4.0,1020.0,SE,1.79,0,0,1.006658,True,no
2/01/2010 1:00,148,-15,-4.0,1020.0,SE,2.68,0,0,1.006658,True,no
2/01/2010 2:00,159,-11,-5.0,1021.0,SE,3.57,0,0,1.007645,True,no
2/01/2010 3:00,181,-7,-5.0,1022.0,SE,5.36,1,0,1.008632,True,no
2/01/2010 4:00,138,-7,-5.0,1022.0,SE,6.25,2,0,1.008632,True,no
...,...,...,...,...,...,...,...,...,...,...,...
31/12/2014 19:00,8,-23,-2.0,1034.0,NW,231.97,0,0,1.020475,True,no
31/12/2014 20:00,10,-22,-3.0,1034.0,NW,237.78,0,0,1.020475,True,no
31/12/2014 21:00,10,-22,-3.0,1034.0,NW,242.70,0,0,1.020475,True,no
31/12/2014 22:00,8,-22,-4.0,1034.0,NW,246.72,0,0,1.020475,True,no
31/12/2014 23:00,12,-21,-3.0,1034.0,NW,249.85,0,0,1.020475,True,no

## Aggregates
Aggregates are used to summarise information in a dataset. They condense many observations down to a single number to describe a property of that variable.

In pandas, these aggregates are stored as methods, meaning the general syntax is <code>df_name.method_name(arguments)</code>.

In [22]:
# find the average pollution
pollution_data.pollution.mean()

np.float64(94.01351598173515)

In [23]:
# find the max pollution. at what time did this occur?
max_pollution = pollution_data.pollution.max()
pollution_data[pollution_data.pollution == max_pollution]

,pollution,dew,temp,press,wnd_dir,wnd_spd,snow,rain,press_atm,is_freezing,is_rain
date,,,,,,,,,,,
23/01/2012 1:00,994,-24,-12.0,1032.0,NW,4.92,0,0,1.018501,True,no

In [24]:
# can also aggregate a dataframe - might need numeric_only argument
pollution_data.mean(numeric_only=True)

pollution        94.013516
dew               1.828516
temp             12.459041
press          1016.447306
wnd_spd          23.894307
snow              0.052763
rain              0.195023
press_atm         1.003152
is_freezing       0.221986
dtype: float64

In [25]:
# find the percentage of observations that have a temperature below zero
below_zero.sum()/len(below_zero) * 100

np.float64(19.61187214611872)